[project]
name = "omaha-range-explorer"
version = "0.1.0"
description = "omaharangeexplorer"
authors = [{ name = "toto", email = "toto@example.com" }]
requires-python = ">=3.10"
dependencies = [
    "matplotlib==3.10.1",
    "mplcursors",
]

[project.optional-dependencies]
dev = ["ruff", "pytest"]

[tool.setuptools]
packages = { find = {} }

[tool.ruff]
line-length = 120
target-version = "py311"
fix = true
exclude = ["venv", ".venv", "build", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "C90"]
ignore = ["C901", "E501"]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["omaha_range_explorer"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["test"]
